version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/Method.Contracts"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
        all-dependencies:
          patterns:
            - "*"
  - package-ecosystem: "nuget"
    directory: "/Test/Method.Contracts.Test"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
        all-dependencies:
          patterns:
            - "*"
  - package-ecosystem: "nuget"
    directory: "/Test/Method.Contracts.Test.DotNetCore"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "System.Text.Json"
    open-pull-requests-limit: 1
    groups:
        all-dependencies:
          patterns:
            - "*"
